"""Add GitHub branch field to Job model

Revision ID: 37a5c8d41cb0
Revises: 862fa80e9a56
Create Date: 2025-07-11 09:52:16.341140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a5c8d41cb0'
down_revision = '862fa80e9a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_branch', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('github_branch')

    # ### end Alembic commands ###
