"""Add partial unique index for posting_id

Revision ID: 4a9edc1fd8a2
Revises: 
Create Date: 2025-06-28 07:57:34.940312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9edc1fd8a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('posting_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_index('ix_job_posting_id_unique', ['posting_id'], unique=True, sqlite_where='posting_id IS NOT NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_posting_id_unique', sqlite_where='posting_id IS NOT NULL')
        batch_op.alter_column('posting_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
