"""Add content_format to job_notes

Revision ID: 862fa80e9a56
Revises: 6c7368b65544
Create Date: 2025-07-10 08:23:21.113134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862fa80e9a56'
down_revision = '6c7368b65544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_format', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_notes', schema=None) as batch_op:
        batch_op.drop_column('content_format')

    # ### end Alembic commands ###
